apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: yashpatelldocker/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
