pipeline {
    agent any

    environment {
        IMAGE_NAME = 'yashpatelldocker/flaskapp'
        TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from repository...'
                checkout scm
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running unit tests...'
                bat 'python test_app.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                bat "docker build -t ${IMAGE_NAME}:${TAG} ."
                bat "docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_NAME}:latest"
            }
        }

        stage('Deploy') {
            steps {
                echo 'Running container...'
                bat "docker stop flask-app || exit 0"
                bat "docker rm flask-app || exit 0"
                bat "docker run -d -p 5000:5000 --name flask-app ${IMAGE_NAME}:${TAG}"
            }
        }
    }

    post {
        always {
            echo 'Build completed.'
        }
    }
}
